// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pawn-broker/AddLoan.tsx": () => import("../components/mockups/pawn-broker/AddLoan.tsx"),
  "./components/mockups/pawn-broker/CustomerList.tsx": () => import("../components/mockups/pawn-broker/CustomerList.tsx"),
  "./components/mockups/pawn-broker/Dashboard.tsx": () => import("../components/mockups/pawn-broker/Dashboard.tsx"),
  "./components/mockups/pawn-broker/LoanDetail.tsx": () => import("../components/mockups/pawn-broker/LoanDetail.tsx"),
  "./components/mockups/pawn-broker/LoanList.tsx": () => import("../components/mockups/pawn-broker/LoanList.tsx"),
  "./components/mockups/pawn-broker/Login.tsx": () => import("../components/mockups/pawn-broker/Login.tsx")
};
